# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuizz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_quizz(self):
    # Test name: quizz
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:5500/ | 
    self.driver.get("http://127.0.0.1:5500/")
    # 2 | setWindowSize | 954x646 | 
    self.driver.set_window_size(954, 646)
    # 3 | click | css=.icon-html > .name | 
    self.driver.find_element(By.CSS_SELECTOR, ".icon-html > .name").click()
    # 4 | click | css=#my_row_1 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_1 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 5 | click | id=submit_1 | 
    self.driver.find_element(By.ID, "submit_1").click()
    # 6 | click | css=#my_row_2 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_2 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 7 | click | id=submit_2 | 
    self.driver.find_element(By.ID, "submit_2").click()
    # 8 | click | css=#my_row_3 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_3 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 9 | click | id=submit_3 | 
    self.driver.find_element(By.ID, "submit_3").click()
    # 10 | click | css=#my_row_4 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_4 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 11 | click | id=submit_4 | 
    self.driver.find_element(By.ID, "submit_4").click()
    # 12 | click | css=#my_row_5 .mb-10:nth-child(3) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_5 .mb-10:nth-child(3) > .font-weight-normal").click()
    # 13 | click | id=submit_5 | 
    self.driver.find_element(By.ID, "submit_5").click()
    # 14 | click | css=#my_row_6 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_6 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 15 | click | id=submit_6 | 
    self.driver.find_element(By.ID, "submit_6").click()
    # 16 | click | css=#my_row_7 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_7 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 17 | click | id=submit_7 | 
    self.driver.find_element(By.ID, "submit_7").click()
    # 18 | click | css=#my_row_8 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_8 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 19 | click | id=submit_8 | 
    self.driver.find_element(By.ID, "submit_8").click()
    # 20 | click | css=#my_row_9 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_9 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 21 | click | id=submit_9 | 
    self.driver.find_element(By.ID, "submit_9").click()
    # 22 | click | css=#my_row_10 .mb-10:nth-child(5) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_10 .mb-10:nth-child(5) > .font-weight-normal").click()
    # 23 | click | id=submit_10 | 
    self.driver.find_element(By.ID, "submit_10").click()
    # 24 | close |  | 
    self.driver.close()
  
