# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGitk():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gitk(self):
    self.driver.get("http://127.0.0.1:5500/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".icon-html > .name").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_1 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_2 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_3 .mb-10:nth-child(4) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_3").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_4 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_4").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_5 .mb-10:nth-child(3) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_5").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_6 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_6").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_7 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_7").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_8 .mb-10:nth-child(2) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_8").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_9 .mb-10:nth-child(5) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_9").click()
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_10 .mb-10:nth-child(5) > .font-weight-normal").click()
    self.driver.find_element(By.ID, "submit_10").click()
  
