# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGitk():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gitk(self):
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git clone\')]").click()
    self.driver.find_element(By.ID, "submit_1").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'A request for code review and merging changes\')]").click()
    self.driver.find_element(By.ID, "submit_2").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'package.json\')]").click()
    self.driver.find_element(By.ID, "submit_3").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'To specify files and directories that should be excluded from version control\')]").click()
    self.driver.find_element(By.ID, "submit_4").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'(url)text\')]").click()
    self.driver.find_element(By.ID, "submit_5").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'To track and discuss problems, enhancements, and ideas related to a project\')]").click()
    self.driver.find_element(By.ID, "submit_6").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git merge\')]").click()
    self.driver.find_element(By.ID, "submit_7").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git reflog\')]").click()
    self.driver.find_element(By.ID, "submit_8").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'gitk\')]").click()
    self.driver.find_element(By.ID, "submit_9").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git reset HEAD~\')]").click()
    self.driver.find_element(By.ID, "submit_10").click()
  
