# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFinal():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_final(self):
    # Test name: final
    # Step # | name | target | value
    # 1 | open | https://www.fastestcoderfirst.com/ | 
    self.driver.get("https://www.fastestcoderfirst.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | css=li:nth-child(6) > .nav-link | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) > .nav-link").click()
    # 4 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | shivani@veersatech.com
    self.driver.find_element(By.ID, "email").send_keys("shivani@veersatech.com")
    # 6 | type | id=password | Veersa@123
    self.driver.find_element(By.ID, "password").send_keys("Veersa@123")
    # 7 | click | name=login | 
    self.driver.find_element(By.NAME, "login").click()
    # 8 | click | linkText=Quiz | 
    self.driver.find_element(By.LINK_TEXT, "Quiz").click()
    # 9 | click | css=.btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
