# Generated by Selenium IDE
import pytest
import time as t
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDd():
  def setup_method(self):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_dd(self):
    # Test name: dd
    # Step # | name | target | value
    # 1 | open | https://www.fastestcoderfirst.com/login | 
    self.driver.get("C:\\Users\\veers\\Desktop\\ms-quiz-auto\\index_1Q.html")
    self.driver.find_element(By.ID, "question-1-answers-A").click()
  # def test_loggedin(self):
  #   self.driver.get("https://www.fastestcoderfirst.com/")
  #   t.sleep(100)
  def login(self):
    self.driver.get("https://www.fastestcoderfirst.com/")
    # 2 | setWindowSize | 1552x832 | 
    self.driver.set_window_size(1552, 832)
    # 3 | click | css=li:nth-child(6) > .nav-link | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) > .nav-link").click()
    # 4 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | shivani@veersatech.com
    self.driver.find_element(By.ID, "email").send_keys("ashish@veersatech.com")
    # 6 | type | id=password | Veersa@123
    self.driver.find_element(By.ID, "password").send_keys("Veersa@123")
    # 7 | click | name=login | 
    self.driver.find_element(By.NAME, "login").click()
    # 8 | click | linkText=Quiz | 
    self.driver.find_element(By.LINK_TEXT, "Quiz").click()

    t.sleep(7)
    # 9 | click | css=.btn | 
  def start_quiz(self):
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_gitk(self):
    # self.driver.get("http://127.0.0.1:5500/index_1Q.html")
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git clone\')]").click()
    self.driver.find_element(By.ID, "submit_1").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'A request for code review and merging changes\')]").click()
    self.driver.find_element(By.ID, "submit_2").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'package.json\')]").click()
    self.driver.find_element(By.ID, "submit_3").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'To specify files and directories that should be excluded from version control\')]").click()
    self.driver.find_element(By.ID, "submit_4").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'(url)text\')]").click()
    self.driver.find_element(By.ID, "submit_5").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'To track and discuss problems, enhancements, and ideas related to a project\')]").click()
    self.driver.find_element(By.ID, "submit_6").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git merge\')]").click()
    self.driver.find_element(By.ID, "submit_7").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git reflog\')]").click()
    self.driver.find_element(By.ID, "submit_8").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'gitk\')]").click()
    self.driver.find_element(By.ID, "submit_9").click()
    self.driver.find_element(By.XPATH, "//label[contains(.,\'git reset HEAD~\')]").click()
    self.driver.find_element(By.ID, "submit_10").click()
    t.sleep(1000);
  def test_quizkardo(self):
    # Test name: quiz kardo
    # Step # | name | target | value
    # 1 | open | /index_1Q.html | 
    # self.driver.get("http://127.0.0.1:5500/index_1Q.html")
    # # 2 | setWindowSize | 1536x864 | 
    # self.driver.set_window_size(1536, 864)


    # # 3 | click | xpath=//label[contains(.,'git clone')] | 
    # self.driver.find_element(By.XPATH, "//label[contains(.,\'git clone\')]").click()
    # # 4 | click | id=submit_1 | 
    # self.driver.find_element(By.ID, "submit_1").click()
    # # 5 | click | xpath=//label[contains(.,'A request for code review and merging changes')] | 
    # self.driver.find_element(By.XPATH, "//label[contains(.,\'A request for code review and merging changes\')]").click()
    # # 6 | click | id=submit_2 | 
    # self.driver.find_element(By.ID, "submit_2").click()
    # # 7 | click | xpath=//label[contains(.,'package.json')] | 
    # self.driver.find_element(By.XPATH, "//label[contains(.,\'package.json\')]").click()
    # # 8 | click | id=submit_3 | 
    # self.driver.find_element(By.ID, "submit_3").click()
    # # 9 | click | xpath=//label[contains(.,'To specify files and directories that should be excluded from version control')] | 
    # self.driver.find_element(By.XPATH, "//label[contains(.,\'To specify files and directories that should be excluded from version control\')]").click()
    # # 10 | click | id=submit_4 | 
    # self.driver.find_element(By.ID, "submit_4").click()
    # # 11 | click | css=#my_row_5 .mb-10:nth-child(4) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_5 .mb-10:nth-child(4) > .font-weight-normal").click()
    # # 12 | click | id=submit_5 | 
    # self.driver.find_element(By.ID, "submit_5").click()
    # # 13 | click | css=#my_row_6 .mb-10:nth-child(2) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_6 .mb-10:nth-child(2) > .font-weight-normal").click()
    # # 14 | click | id=submit_6 | 
    # self.driver.find_element(By.ID, "submit_6").click()
    # # 15 | click | css=#my_row_7 .mb-10:nth-child(2) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_7 .mb-10:nth-child(2) > .font-weight-normal").click()
    # # 16 | click | id=submit_7 | 
    # self.driver.find_element(By.ID, "submit_7").click()
    # # 17 | click | css=#my_row_8 .mb-10:nth-child(2) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_8 .mb-10:nth-child(2) > .font-weight-normal").click()
    # # 18 | click | id=submit_8 | 
    # self.driver.find_element(By.ID, "submit_8").click()
    # # 19 | click | css=#my_row_9 .mb-10:nth-child(2) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_9 .mb-10:nth-child(2) > .font-weight-normal").click()
    # # 20 | click | id=submit_9 | 
    # self.driver.find_element(By.ID, "submit_9").click()
    # # 21 | click | css=#my_row_10 .mb-10:nth-child(5) > .font-weight-normal | 
    # self.driver.find_element(By.CSS_SELECTOR, "#my_row_10 .mb-10:nth-child(5) > .font-weight-normal").click()
    # # 22 | click | id=submit_10 | 
    # self.driver.find_element(By.ID, "submit_10").click()


    # other answers

    self.driver.find_element(By.CSS_SELECTOR, "#my_row_1 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 5 | click | id=submit_1 | 
    self.driver.find_element(By.ID, "submit_1").click()
    # 6 | click | css=#my_row_2 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_2 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 7 | click | id=submit_2 | 
    self.driver.find_element(By.ID, "submit_2").click()
    # 8 | click | css=#my_row_3 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_3 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 9 | click | id=submit_3 | 
    self.driver.find_element(By.ID, "submit_3").click()
    # 10 | click | css=#my_row_4 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_4 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 11 | click | id=submit_4 | 
    self.driver.find_element(By.ID, "submit_4").click()
    # 12 | click | css=#my_row_5 .mb-10:nth-child(3) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_5 .mb-10:nth-child(3) > .font-weight-normal").click()
    # 13 | click | id=submit_5 | 
    self.driver.find_element(By.ID, "submit_5").click()
    # 14 | click | css=#my_row_6 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_6 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 15 | click | id=submit_6 | 
    self.driver.find_element(By.ID, "submit_6").click()
    # 16 | click | css=#my_row_7 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_7 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 17 | click | id=submit_7 | 
    self.driver.find_element(By.ID, "submit_7").click()
    # 18 | click | css=#my_row_8 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_8 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 19 | click | id=submit_8 | 
    self.driver.find_element(By.ID, "submit_8").click()
    # 20 | click | css=#my_row_9 .mb-10:nth-child(2) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_9 .mb-10:nth-child(2) > .font-weight-normal").click()
    # 21 | click | id=submit_9 | 
    self.driver.find_element(By.ID, "submit_9").click()
    # 22 | click | css=#my_row_10 .mb-10:nth-child(5) > .font-weight-normal | 
    self.driver.find_element(By.CSS_SELECTOR, "#my_row_10 .mb-10:nth-child(5) > .font-weight-normal").click()
    # 23 | click | id=submit_10 | 
    self.driver.find_element(By.ID, "submit_10").click()
  
    

    t.sleep(2000)
    # 2 | setWindowSize | 962x658 | 
    # self.driver.set_window_size(962, 658)
    # # 3 | click | id=email | 
    # # 4 | type | id=email | shivani@veersatech.com
    # self.driver.find_element(By.ID, "email").send_keys("shivani@veersatech.com")
    # # 5 | type | id=password | Veersa@123
    # self.driver.find_element(By.ID, "password").send_keys("Veersa@123")
    # # 6 | click | name=login | 
    # self.driver.find_element(By.NAME, "login").click()
    # # 7 | click | linkText=Quiz | 
    # self.driver.find_element(By.LINK_TEXT, "Quiz").click()
  
obj = TestDd()
obj.setup_method()
# obj.test_dd()
obj.login()
obj.start_quiz()
obj.test_gitk()
# obj.test_quizkardo()

# obj.test_loggedin()
# obj.test_quizkardo()